## 학습목표
 1. 브로드캐스팅의 이해
     - shape 이 달라도 더해주는 것

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

**뒤에 있는 차원이 동일하면 계산해준다

In [3]:
import numpy as np

- Shape 이 같은 경우의 연산

In [12]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.68746156 0.6979375  0.35613436 0.55309699 0.17744339]
 [0.63728785 0.62046761 0.59527146 0.2554983  0.4568534 ]
 [0.40375071 0.4467239  0.15122791 0.22811905 0.18245855]]


In [5]:
x+y

array([[ 0.66412461,  1.12515376,  2.37738477,  3.73483212,  4.43445951],
       [ 5.48162841,  6.05255445,  7.1161369 ,  8.49828658,  9.39124667],
       [10.574434  , 11.55199116, 12.32398148, 13.47844792, 14.35165874]])

* Scalar(상수)와의 연산

In [13]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
x+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [15]:
x**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [16]:
x%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [26]:
a=np.arange(12).reshape(4,3)
b=np.arange(100,103)
c=np.arange(1000,1004)
d=b.reshape(1,3)
print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)
print(c.shape)
print(d.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[100 101 102]
(3,)
[1000 1001 1002 1003]
(4,)
(1, 3)


In [18]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [22]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [27]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])