## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함 ****

In [3]:
x=np.random.rand(3,3)
x

array([[0.32830748, 0.27753724, 0.34668466],
       [0.56847666, 0.70490635, 0.9126252 ],
       [0.49418468, 0.37770636, 0.45023414]])

In [6]:
# 역행렬
new_x=np.linalg.inv(x)

In [8]:
# 행렬끼리의 곱은 np.matmul 혹은 @ 사용 
x @ new_x

array([[1.00000000e+00, 4.44089210e-16, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [7.10542736e-15, 0.00000000e+00, 1.00000000e+00]])

In [9]:
np.matmul(x,new_x)

array([[1.00000000e+00, 4.44089210e-16, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [7.10542736e-15, 0.00000000e+00, 1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [10]:
A=np.array([[1,1],[2,4]])
B=np.array([25,64])
x=np.linalg.solve(A,B)
print(x)

[18.  7.]


In [13]:
# 실수값을 비교할 때 사용하는 모듈
np.allclose(A@x,B)

True