In [1]:
import numpy as np

#### 인덱싱
- 파이썬 리스트와 동일한 개념
- , 를 사용하여 각 차원의 인덱스에 접근 가능

In [2]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[3]

3

In [4]:
x[3]=100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


#### 2차원 행렬 인덱싱

In [6]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# 첫번째 행, 벡터
x[0]

array([0, 1, 2, 3, 4])

In [12]:
# 0 번째 행의 2 번째 열
x[0][2]

2

#### 3차원 행렬 인덱싱

In [17]:
x=np.arange(36).reshape(3,4,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [21]:
# 첫 번째 차원
x[0]  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# 첫 번째 차원의 첫번째 행
x[0][0]

array([0, 1, 2])

In [24]:
x[1,2]

array([18, 19, 20])

In [26]:
# 첫 번째 차원의 첫번째 원소
x[0][0][0]


0

In [27]:
x[0,0,0]

0

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

In [29]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
x[2:5]

array([2, 3, 4])

In [31]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- 2차원 행렬 슬라이싱

In [33]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [41]:
x[1,:2]

array([5, 6])

In [36]:
# 전체의, 1~3 번째 원소
x[:,1:4]

array([[1, 2, 3],
       [6, 7, 8]])

* 3차원 텐서 슬라이싱

In [44]:
x = np.arange(54).reshape(3, 3, 6)
print(x)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]]]


In [45]:
x[:1,:1,:5]

array([[[0, 1, 2, 3, 4]]])

In [47]:
x[0,0,:5]
# 인덱싱을 하면 차원이 변한다

array([0, 1, 2, 3, 4])