In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [7]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.61198025 0.2208403  0.70627979 0.72374685 0.69655863]
 [0.00830857 0.6018524  0.02024542 0.90270252 0.08690239]
 [0.72050866 0.6518318  0.64926934 0.97606451 0.13098771]]


#### 연산 함수
- add, substract, multiply, divide
- shape 의 값이 같아야한다

In [12]:
x+y

array([[ 0.61198025,  1.2208403 ,  2.70627979,  3.72374685,  4.69655863],
       [ 5.00830857,  6.6018524 ,  7.02024542,  8.90270252,  9.08690239],
       [10.72050866, 11.6518318 , 12.64926934, 13.97606451, 14.13098771]])

In [8]:
np.add(x,y)

array([[ 0.61198025,  1.2208403 ,  2.70627979,  3.72374685,  4.69655863],
       [ 5.00830857,  6.6018524 ,  7.02024542,  8.90270252,  9.08690239],
       [10.72050866, 11.6518318 , 12.64926934, 13.97606451, 14.13098771]])

In [9]:
np.subtract(x,y)

array([[-0.61198025,  0.7791597 ,  1.29372021,  2.27625315,  3.30344137],
       [ 4.99169143,  5.3981476 ,  6.97975458,  7.09729748,  8.91309761],
       [ 9.27949134, 10.3481682 , 11.35073066, 12.02393549, 13.86901229]])

In [10]:
np.multiply(x,y)

array([[ 0.        ,  0.2208403 ,  1.41255959,  2.17124055,  2.78623451],
       [ 0.04154285,  3.61111439,  0.14171797,  7.22162019,  0.78212155],
       [ 7.2050866 ,  7.17014978,  7.79123212, 12.68883867,  1.83382799]])

In [11]:
np.divide(x,y)

array([[  0.        ,   4.52815897,   2.83173895,   4.14509577,
          5.74251735],
       [601.78834186,   9.96922171, 345.75714121,   8.86227721,
        103.56446554],
       [ 13.8790837 ,  16.87551915,  18.48231419,  13.31879176,
        106.88025305]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [13]:
print(y)

[[0.61198025 0.2208403  0.70627979 0.72374685 0.69655863]
 [0.00830857 0.6018524  0.02024542 0.90270252 0.08690239]
 [0.72050866 0.6518318  0.64926934 0.97606451 0.13098771]]


In [14]:
# y.mean() 과 동일
np.mean(y)

0.5138719439572523

In [15]:
y.mean()

0.5138719439572523

In [17]:
# y의 가장 큰 값
print(np.max(y))
# y의 가장 큰 값의 인덱스
print(np.argmax(y))

0.9760645133234223
13


In [19]:
# 분산       중앙          표준편차
np.var(y), np.median(y), np.std(y)

(0.0993810746690413, 0.6492693435848448, 0.31524764022755397)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [20]:
y

array([[0.61198025, 0.2208403 , 0.70627979, 0.72374685, 0.69655863],
       [0.00830857, 0.6018524 , 0.02024542, 0.90270252, 0.08690239],
       [0.72050866, 0.6518318 , 0.64926934, 0.97606451, 0.13098771]])

In [22]:
np.sum(y)

7.708079159358785

In [24]:
# 그래프 그릴 때 누적값 활용도 UP!!
np.cumsum(y)

array([0.61198025, 0.83282055, 1.53910035, 2.26284719, 2.95940582,
       2.96771439, 3.56956679, 3.58981221, 4.49251474, 4.57941713,
       5.29992579, 5.95175759, 6.60102693, 7.57709145, 7.70807916])

In [29]:
print(np.sum(y, axis=None))
print(np.sum(y, axis=1)) # 행을 기준으로 더한다
print(np.sum(y, axis=0)) # 열을 기준으로 더한다

7.708079159358785
[2.95940582 1.62001131 3.12866203]
[1.34079748 1.4745245  1.37579456 2.60251389 0.91444873]


#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [30]:
z=np.random.randn(10)
print(z)

[-0.35125238  0.53689102  1.53379045  1.6273337  -0.23844503  1.29945348
  0.40743737 -1.11418813 -0.98321073  0.05880238]


In [31]:
z>0

array([False,  True,  True,  True, False,  True,  True, False, False,
        True])

In [40]:
# 1개라도 조건 만족하면?
np.any(z>0)

True

In [42]:
# 모든 값들이 조건 만족하면?
np.all(z>0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [47]:
z=np.random.randn(10)
print(z)

[ 1.20143324 -0.55471595 -0.89155368  0.21870045  0.14400935  0.31984902
 -0.66297929  0.47496618  0.94643372  1.0839354 ]


In [48]:
# z>0 인 경우 z, 아니면 0 을 출력
np.where(z>0, z, 0)

array([1.20143324, 0.        , 0.        , 0.21870045, 0.14400935,
       0.31984902, 0.        , 0.47496618, 0.94643372, 1.0839354 ])