#### random 서브모듈

In [1]:
import numpy as np
import matplotlib.pyplot as plt 

#### rand 함수
- 0,1 사이의 분포로 랜덤한 ndarray생성

In [25]:
np.random.rand(2,3)
# 2행 3열의 랜덤한 값 지정

array([[0.08141228, 0.02106483, 0.15218844],
       [0.50455066, 0.85659108, 0.1396198 ]])

In [27]:
np.random.rand(2,4,3)

array([[[0.16487974, 0.52818655, 0.09239593],
        [0.84879977, 0.22761842, 0.94969789],
        [0.90641133, 0.70840461, 0.55520568],
        [0.45988249, 0.59431871, 0.61608855]],

       [[0.06541167, 0.86056328, 0.33037967],
        [0.03895755, 0.25202138, 0.79345202],
        [0.92705762, 0.67365862, 0.77058739],
        [0.37372126, 0.55242895, 0.13955732]]])

#### randn 함수
- n : norbal distribution (정규분포) 구할때 사용
- 정규분포로 샘플링된 랜덤 dnarray 생성

In [28]:
np.random.randn(3,4)

array([[-0.2741849 , -0.72318023,  0.17249428, -0.03315082],
       [ 0.08728933,  0.19475759, -0.93101929, -0.15323818],
       [-0.5523062 , -0.48402767, -0.87124151,  0.61522888]])