#### 연습문제
 1. 로또 번호 자동 생성기(함수로)를 만드시오
 2. numpy를 이용하여 pi(원주율) 값을 계산하시오
  - 몬테 카를로 방법 이용하기
      - 난수를 발견시켜 근사값을 구한다
  - ![파이 값 구하기](http://mathfaculty.fullerton.edu/mathews/n2003/montecarlopi/MonteCarloPiMod/Images/MonteCarloPiMod_gr_25.gif)
  - 이미지 출처: http://mathfaculty.fullerton.edu/mathews/n2003/montecarlopi/MonteCarloPiMod/Images/MonteCarloPiMod_gr_25.gif 

# 1번 문제 풀이

In [1]:
import numpy as np

In [11]:
def generate_lotto_nums():
    return np.random.choice(np.arange(1,46),size=6, replace=False)

In [20]:
generate_lotto_nums()

array([19, 44,  3, 18, 38, 27])

# 2번 문제 풀이

In [23]:
import matplotlib.pyplot as plt
%matplotlib inline

pi/4 : 1 = (4분원 안에 생성된 점 개수) : 전체 시도 횟수

pi= 4 * (4분원 안에 생성된 점 개수) / 전체 시도 횟수 (천만번 : 1e7 )

In [26]:
total=int(1e7) # 전체개수

In [30]:
points=np.random.rand(total,2) #
print(points)
print(points.shape)

[[0.98088749 0.20796516]
 [0.08552969 0.35949678]
 [0.02541759 0.25926395]
 ...
 [0.46357811 0.87350505]
 [0.74485884 0.46420688]
 [0.61347384 0.39141174]]
(10000000, 2)


In [35]:
a=np.sum(points**2,axis=1)
print(a)

[1.00538979 0.13655327 0.06786385 ... 0.97791574 0.77030271 0.52955331]


In [34]:
# 원은 x,y 의 제곱의 합이 반지름과 동일
np.sum(points**2,axis=1) <1

array([False,  True,  True, ...,  True,  True,  True])

In [37]:
print(a[a<1])
print(len(a))

[0.13655327 0.06786385 0.2748942  ... 0.97791574 0.77030271 0.52955331]
10000000


In [41]:
total=int(1e7)
points=np.random.rand(total,2)
4*np.sum(np.sum(points**2, axis=1) <1) / total

3.1410704